CONFIG = {
    "NUM_FREQ_BANDS": 80,
    "NUM_TIME_BANDS": 15,
    "NUM_MULTI_CHANNELS": 3,
    "SAMPLE_RATE": 44100,
    "MIN_FREQ": 27.5,
    "MAX_FREQ": 16000,
    "STFT_HOP_LENGTH_SECONDS": 0.010,
    "STFT_WINDOW_LENGTH_SECONDS": 0.025,
    "NUM_ARROW_TYPES": 4
}

VGGISH_CONFIG = {
    "NUM_FREQ_BANDS": 64,
    "NUM_TIME_BANDS": 96,
    "NUM_MULTI_CHANNELS": 3,
    "SAMPLE_RATE": 16000,
    "MIN_FREQ": 125,
    "MAX_FREQ": 7500,
    "STFT_HOP_LENGTH_SECONDS": 0.010,
    "STFT_WINDOW_LENGTH_SECONDS": 0.025,
    "NUM_ARROW_TYPES": 4
}
