SAMPLE_RATE = 44100

HOPSIZE_T = 0.010

MULTI_CHANNEL_FRAME_SIZES = [1024, 2048, 4096]

SINGLE_CHANNEL_FRAME_SIZE = 2048

NUM_MULTI_CHANNELS = len(MULTI_CHANNEL_FRAME_SIZES)

NUM_FREQ_BANDS = 80

NUM_TIME_BANDS = 15

THRESHOLDS = {'expert': 0.5}

NUM_ARROW_TYPES = 4

ARROW_NAMES = ["left_arrow", "down_arrow", "up_arrow", "right_arrow"]

NUM_ARROWS = len(ARROW_NAMES)
