"""Hyperparameters for DDC step placement (`donahue2017ddc`)."""

from stepcovnet.dataset_prep import constants as prep_constants

SAMPLE_RATE = 44100
FRAME_RATE = 100
HOP_LENGTH = SAMPLE_RATE // FRAME_RATE
HOP_SEC = 1.0 / FRAME_RATE
N_MELS = 80
# 1024/2048/4096 samples at 44.1 kHz ≈ 23/46/93 ms (`hamel2012multiscale`).
FFT_SIZES = (1024, 2048, 4096)
N_CHANNELS = len(FFT_SIZES)
CONTEXT_RADIUS = 7
CONTEXT_FRAMES = CONTEXT_RADIUS * 2 + 1
N_DIFFICULTIES = 5
DIFFICULTY_LABELS = (
    "beginner",
    "easy",
    "medium",
    "hard",
    "challenge",
)
STANDARD_DIFFICULTIES = prep_constants.STANDARD_DIFFICULTIES
HAMMING_WIDTH = 5
ALIGN_TOLERANCE_FRAMES = 2
ALIGN_TOLERANCE_SEC = ALIGN_TOLERANCE_FRAMES * HOP_SEC
NUNROLL = 100
LSTM_UNITS = 200
LSTM_LAYERS = 2
DNN_SIZES = (256, 128)
CNN_FILTERS = (10, 20)
CNN_KERNELS = ((7, 3), (3, 3))
CNN_POOL = (1, 3)
DROPOUT_RATE = 0.5
PAPER_BATCH_SIZE = 256
PAPER_SGD_LR = 0.1
PAPER_CLIPNORM = 5.0
PAPER_F_SCORE_C = 0.681
PAPER_F_SCORE_M = 0.756
PREDICT_CHUNK_FRAMES = 256
FEATURE_CACHE_SUFFIX = ".ddc_mel.npy"
LOG_EPS = 1e-16
